version: '3.8'

services:
  bot:
    build: .
    container_name: telegram-reminder-bot
    restart: unless-stopped
    env_file: .env
    environment:
      - NODE_ENV=production
    volumes:
      - ./logs:/app/logs